# Generated by Django 4.1.2 on 2022-10-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_description_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.catagory'),
        ),
    ]
