# Generated by Django 4.1.2 on 2022-10-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='catagory',
        ),
        migrations.AddField(
            model_name='blog',
            name='catagories',
            field=models.ManyToManyField(related_name='blog', to='blog.catagory'),
        ),
    ]
